name: "terarform-infra-plan"

on:
  workflow_dispatch:
    inputs:
      destination_environment:
        type: environment
  workflow_call:
    inputs:
      destination_environment:
        type: string


jobs:
  terraform-plan:
    name: "Terraform-Plan"
    runs-on: ubuntu-latest
    environment: ${{ inputs.destination_environment }}


    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - id: string
        uses: ASzc/change-string-case-action@v5
        with:
          string: aws_access_key_id

      - name: Configure AWS credentials
        env : 
          AWS_ACCESS_KEY_ID_NAME : ${{ steps.string.outputs.uppercase }}
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets[ env.AWS_ACCESS_KEY_ID_NAME] }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY}}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Setup Terraform CLI
        uses: hashicorp/setup-terraform@v2

      - name: Terraform init
        run: |
          echo "** Running Terraform Init **"
          terraform init

      - name: Terraform Validate
        run: |
          echo "** Running Terraform Validate **"
          terraform validate

      - name: Terraform Plan
        run: |
          echo "** Running Terraform Plan **"
          pwd
          terraform plan -out=myplan

  

      - name: Publish artifact
        uses: actions/upload-artifact@v3
        with:
          name: published-app
          path: ./
  terraform-apply:
    name: "Terraform-Apply"
    uses: ./.github/workflows/deploy.yml
    with:
      destination_environment: ${{ inputs.environment }}
    secrets: inherit
    needs: terraform-plan


 
