name: "terarform-infra-plan"

on:
  workflow_dispatch:
    inputs:
      destination_environment:
        type: environment
  workflow_call:
    inputs:
      destination_environment:
        type: string


jobs:
  terraform-apply:
    name: "Terraform-Apply"
    runs-on: ubuntu-latest
    environment: deploy
  

    steps:
      # Download published artifact
      - name: Checkout
        uses: actions/checkout@v3
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Setup Terraform CLI
        uses: hashicorp/setup-terraform@v2
      - name: Terraform init
        run: |
          echo "** Running Terraform Init **"
          rm -rf .terraform/
          terraform init          
      - name: Terraform Apply
        run: |
          echo "** Running Terraform Plan **"
          cat main.tf

          ls -al
          terraform apply 
